# Generated by Django 2.2 on 2020-11-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Disponible', 'D'), ('Ocupado', 'O')], default='Disponible', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_noche', models.IntegerField()),
                ('num_habitacion', models.IntegerField()),
                ('cant_dormitorios', models.IntegerField()),
                ('cant_banios', models.IntegerField()),
                ('tipo_habitacion', models.CharField(choices=[('Suite', 'S'), ('Matrimonial', 'M'), ('Individual', 'I'), ('Familiar', 'F'), ('Normal', 'N'), ('Presidencial', 'P')], default='Normal', max_length=50)),
                ('img_habitacion', models.ImageField(blank=True, upload_to='img_habitacion/')),
                ('estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.Estado')),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Proyecto.Persona')),
                ('codigo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
            bases=('Proyecto.persona',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Proyecto.Persona')),
                ('codigo', models.CharField(max_length=20)),
            ],
            bases=('Proyecto.persona',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estrellas', models.IntegerField()),
                ('direccion', models.CharField(blank=True, default=None, max_length=50)),
                ('habitaciones', models.ManyToManyField(blank=True, default=None, to='Proyecto.Habitacion')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.Cliente'),
        ),
    ]
