# Generated by Django 2.2 on 2020-11-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='reservas',
            field=models.ManyToManyField(blank=True, default=None, to='Proyecto.Habitacion'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'D'), ('Ocupado', 'O')], default='Disponible', max_length=50),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
