# Generated by Django 2.2 on 2020-11-02 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='estado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.Estado'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipohabitacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.TipoHabitacion'),
        ),
    ]
