# Generated by Django 2.2 on 2020-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0002_auto_20201102_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='img_habitacion',
            field=models.ImageField(blank=True, upload_to='img_habitacion/'),
        ),
    ]
