# Generated by Django 2.2 on 2020-11-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0002_hotel_vista_previa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='vista_previa',
            field=models.ImageField(blank=True, default='img_hotel/default.jpg', upload_to='img_hotel/'),
        ),
    ]
