# Generated by Django 2.2 on 2020-11-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0003_auto_20201122_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='vista_previa',
            field=models.ImageField(blank=True, default='img_hotel/default.png', upload_to='img_hotel/'),
        ),
    ]
