# Generated by Django 2.2 on 2020-11-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0003_habitacion_img_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.Direccion'),
            preserve_default=False,
        ),
    ]
