# Generated by Django 2.2 on 2020-11-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0010_auto_20201112_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='direccion',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
