# Generated by Django 2.2 on 2020-11-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0010_auto_20201122_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='img_hotel',
            field=models.ImageField(blank=True, default='/img_hoteles/hotel-generic.jpg', null=True, upload_to='img_hoteles/'),
        ),
    ]
