# Generated by Django 2.2 on 2020-11-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0011_auto_20201122_1910'),
        ('Proyecto', '0004_auto_20201122_1312'),
    ]

    operations = [
    ]
