# Generated by Django 2.2 on 2020-11-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0012_merge_20201124_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='vista_previa',
        ),
    ]
