# Generated by Django 2.2 on 2020-11-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0013_remove_hotel_vista_previa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='img_habitacion',
            field=models.ImageField(blank=True, default='/img_habitaciones/habitacion_prueba.jpg', null=True, upload_to='img_habitacion/'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='num_habitacion',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.CharField(choices=[('Suite', 'Suite'), ('Matrimonial', 'Matrimonial'), ('Individual', 'Individual'), ('Familiar', 'Familiar'), ('Normal', 'Normal'), ('Presidencial', 'Presidencial')], default='Normal', max_length=50),
        ),
    ]
