# Generated by Django 2.2 on 2020-11-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0014_auto_20201125_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='num_habitacion',
            field=models.CharField(max_length=5),
        ),
    ]
