# Generated by Django 2.2 on 2020-11-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0004_persona_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
    ]
