# Generated by Django 2.2 on 2020-11-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0007_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hoteles'},
        ),
    ]
