# Generated by Django 2.2 on 2020-11-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0008_auto_20201112_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='habitaciones',
        ),
        migrations.AddField(
            model_name='hotel',
            name='habitaciones',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='Proyecto.Habitacion'),
        ),
    ]
