# Generated by Django 2.2 on 2020-11-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0009_auto_20201112_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='habitaciones',
            field=models.ManyToManyField(blank=True, default=None, to='Proyecto.Habitacion'),
        ),
    ]
