# Generated by Django 2.2 on 2020-11-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0011_auto_20201113_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='tipohabitacion',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.CharField(choices=[('Suite', 'S'), ('Matrimonial', 'M'), ('Individual', 'I'), ('Familiar', 'F'), ('Normal', 'N'), ('Presidencial', 'P')], default='Normal', max_length=50),
        ),
        migrations.DeleteModel(
            name='TipoHabitacion',
        ),
    ]
