# Generated by Django 2.2 on 2020-11-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0012_auto_20201113_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='cantBanios',
            new_name='cant_banios',
        ),
        migrations.RenameField(
            model_name='habitacion',
            old_name='cantDormitorios',
            new_name='cant_dormitorios',
        ),
        migrations.RenameField(
            model_name='habitacion',
            old_name='numHabitacion',
            new_name='num_habitacion',
        ),
        migrations.RenameField(
            model_name='habitacion',
            old_name='precioNoche',
            new_name='precio_noche',
        ),
    ]
